### ISSUE TITLE
WorldListener error (reported by customer)

### ISSUE THREAD

**Issue by Vagdedes** [Vagdedes/Spartan-AntiCheat#20]
[Sun 20:33:51 ERROR Minecraft] [Spartan] Unhandled exception number 512 occurred in onPacketSending(PacketEvent) for Spartan
FieldAccessException: Field index 0 is out of bounds for length 0
    at com.comphenix.protocol.reflect.FieldAccessException.fromFormat(FieldAccessException.java:49)
    at com.comphenix.protocol.reflect.StructureModifier.read(StructureModifier.java:247)
    at com.vagdedes.spartan.listeners.protocol.g.onPacketSending(WorldListener.java:54)
    at com.comphenix.protocol.injector.collection.OutboundPacketListenerSet.invokeListener(OutboundPacketListenerSet.java:74)
    at com.comphenix.protocol.injector.collection.PacketListenerSet.lambda$invoke$0(PacketListenerSet.java:120)
    at com.comphenix.protocol.timing.TimingTracker.lambda$static$0(TimingTracker.java:7)
    at com.comphenix.protocol.injector.collection.PacketListenerSet.invoke(PacketListenerSet.java:120)
    at com.comphenix.protocol.injector.collection.OutboundPacketListenerSet.invoke(OutboundPacketListenerSet.java:30)
    at com.comphenix.protocol.injector.collection.PacketListenerSet.invoke(PacketListenerSet.java:99)
    at com.comphenix.protocol.injector.PacketFilterManager.postPacketToListeners(PacketFilterManager.java:543)
    at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:517)
    at com.comphenix.protocol.injector.netty.manager.NetworkManagerInjector.onPacketSending(NetworkManagerInjector.java:74)
    at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.processOutbound(NettyChannelInjector.java:548)
    at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.proxyRunnable(NettyEventLoopProxy.java:44)
    at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.execute(NettyEventLoopProxy.java:233)

**Comment by kireikosasha** [comment]
not full stacktrace, improssible to fix

**Comment by Vagdedes** [comment]
This is the original: https://pastebin.com/H7Ugu0sT

I will ask if there's an extended version

**Comment by Vagdedes** [comment]
# **Full error:**

[Spartan] Unhandled exception number 2048 occurred in onPacketSending(PacketEvent) for Spartan
com.comphenix.protocol.reflect.FieldAccessException: Field index 0 is out of bounds for length 0
        at com.comphenix.protocol.reflect.FieldAccessException.fromFormat(FieldAccessException.java:49) ~[?:?]
        at com.comphenix.protocol.reflect.StructureModifier.read(StructureModifier.java:247) ~[?:?]
        at com.vagdedes.spartan.listeners.protocol.g.onPacketSending(WorldListener.java:54) ~[?:?]
        at com.comphenix.protocol.injector.collection.OutboundPacketListenerSet.invokeListener(OutboundPacketListenerSet.java:74) ~[?:?]
        at com.comphenix.protocol.injector.collection.PacketListenerSet.lambda$invoke$0(PacketListenerSet.java:120) ~[?:?]
        at com.comphenix.protocol.timing.TimingTracker.lambda$static$0(TimingTracker.java:7) ~[?:?]
        at com.comphenix.protocol.injector.collection.PacketListenerSet.invoke(PacketListenerSet.java:120) ~[?:?]
        at com.comphenix.protocol.injector.collection.OutboundPacketListenerSet.invoke(OutboundPacketListenerSet.java:30) ~[?:?]
        at com.comphenix.protocol.injector.collection.PacketListenerSet.invoke(PacketListenerSet.java:99) ~[?:?]
        at com.comphenix.protocol.injector.PacketFilterManager.postPacketToListeners(PacketFilterManager.java:543) ~[?:?]
        at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:517) ~[?:?]
        at com.comphenix.protocol.injector.netty.manager.NetworkManagerInjector.onPacketSending(NetworkManagerInjector.java:74) ~[?:?]
        at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.processOutbound(NettyChannelInjector.java:548) ~[?:?]
        at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.proxyRunnable(NettyEventLoopProxy.java:44) ~[?:?]
        at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.execute(NettyEventLoopProxy.java:233) ~[?:?]
at net.minecraft.network.NetworkManager.b(NetworkManager.java:366) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4232-Spigot-1aabe50-820084b]
        at net.minecraft.network.NetworkManager.a(NetworkManager.java:342) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4232-Spigot-1aabe50-820084b]
        at net.minecraft.server.network.ServerCommonPacketListenerImpl.a(ServerCommonPacketListenerImpl.java:266) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4232-Spigot-1aabe50-820084b]
        at net.minecraft.server.network.ServerCommonPacketListenerImpl.b(ServerCommonPacketListenerImpl.java:247) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4232-Spigot-1aabe50-820084b]
        at net.minecraft.server.network.PlayerChunkSender.a(SourceFile:79) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4232-Spigot-1aabe50-820084b]
        at net.minecraft.server.MinecraftServer.c(MinecraftServer.java:1511) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4232-Spigot-1aabe50-820084b]
        at net.minecraft.server.dedicated.DedicatedServer.c(DedicatedServer.java:406) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4232-Spigot-1aabe50-820084b]
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1321) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4232-Spigot-1aabe50-820084b]
        at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1071) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4232-Spigot-1aabe50-820084b]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4232-Spigot-1aabe50-820084b]
        at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]

**Comment by Vagdedes** [comment]
Fixed due to the removal of World Listener
