### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by ImYenil** [Vagdedes/Spartan-AntiCheat#32]
[23:37:12 ERROR]: Could not pass event WorldUnloadEvent to Spartan vPhase 536.3
java.lang.NullPointerException: Cannot invoke "java.util.Map.values()" because "subMap" is null
        at com.vagdedes.spartan.listeners.a.b.a(Event_Chunks.java:203) ~[Spartan.jar:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:git-Paper-196]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.1.jar:git-Paper-196]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.1.jar:git-Paper-196]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.unloadWorld(CraftServer.java:1387) ~[paper-1.20.1.jar:git-Paper-196]
        at org.bukkit.Bukkit.unloadWorld(Bukkit.java:832) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at Utils.WorldReset.unloadWorld(WorldReset.java:99) ~[Zombies-1.8.2.jar:?]
        at Utils.WorldReset.reset(WorldReset.java:41) ~[Zombies-1.8.2.jar:?]
        at Zombies.GameArena$17$1$1.run(GameArena.java:4049) ~[Zombies-1.8.2.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.1.jar:git-Paper-196]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1479) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:446) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1393) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1170) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.20.1.jar:git-Paper-196]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]

**Comment by Vagdedes** [comment]
Fixed for the next update
