### ISSUE TITLE
ExceptionInInitializerError

### ISSUE THREAD

**Issue by ImYenil** [Vagdedes/Spartan-AntiCheat#40]
[15:01:23 WARN]: [ProtocolLib] Error filtering reports: java.lang.IllegalArgumentException: Cannot find report name for Plugin %s tried to register listener for unknown packet %s [direction: from %s]
[15:01:23 WARN]: [ProtocolLib] [OutboundPacketListenerSet] Plugin Spartan tried to register listener for unknown packet DAMAGE_EVENT[PLAY, SERVER, 26, classNames: [net.minecraft.server.v1_8_R3.PacketPlayOutDamageEvent, net.minecraft.network.protocol.game.ClientboundDamageEventPacket, PacketPlayOutDamageEvent, ClientboundDamageEventPacket, DamageEvent, net.minecraft.server.v1_8_R3.PacketPlayOutClientboundDamageEventPacket, net.minecraft.network.protocol.game.ClientboundClientboundDamageEventPacketPacket, PacketPlayOutClientboundDamageEventPacket, ClientboundClientboundDamageEventPacketPacket, ClientboundDamageEventPacket] (unregistered)] [direction: from SERVER]
[15:01:23 ERROR]: [Spartan] Plugin Spartan vPhase 536.4 has failed to register events for class com.vagdedes.spartan.listeners.a.b because org/bukkit/block/data/BlockData does not exist.
[15:01:23 INFO]: Server permissions file permissions.yml is empty, ignoring it
[15:01:23 INFO]: Done (6.411s)! For help, type "help" or "?"
[15:01:23 INFO]: [Carbon] Timings Reset
[15:01:50 INFO]: UUID of player ImYenil_ is 31b67454-30d1-400b-8dc9-b03017813f70
[15:01:50 INFO]: ImYenil_ logged in with entity id 1267 at ([world]185.5, 60.0, 30.5)
[15:01:56 INFO]: ImYenil_ issued server command: /spartan
[15:01:57 ERROR]: [Spartan] Unhandled exception occurred in onPacketReceiving(PacketEvent) for Spartan
java.lang.ExceptionInInitializerError: null
        at com.comphenix.protocol.events.AbstractStructure.getEnumEntityUseActions(AbstractStructure.java:667) ~[?:?]
        at com.vagdedes.spartan.listeners.protocol.a.a(Attack.java:58) ~[?:?]
        at com.vagdedes.spartan.listeners.protocol.a.onPacketReceiving(Attack.java:38) ~[?:?]
        at com.comphenix.protocol.injector.collection.InboundPacketListenerSet.invokeListener(InboundPacketListenerSet.java:25) ~[?:?]
        at com.comphenix.protocol.injector.collection.PacketListenerSet.lambda$invoke$0(PacketListenerSet.java:120) ~[?:?]
        at com.comphenix.protocol.timing.TimingTracker.lambda$static$0(TimingTracker.java:7) ~[?:?]
        at com.comphenix.protocol.injector.collection.PacketListenerSet.invoke(PacketListenerSet.java:120) ~[?:?]
        at com.comphenix.protocol.injector.collection.PacketListenerSet.invoke(PacketListenerSet.java:99) ~[?:?]
        at com.comphenix.protocol.injector.PacketFilterManager.postPacketToListeners(PacketFilterManager.java:528) ~[?:?]
        at com.comphenix.protocol.injector.PacketFilterManager.invokeInboundPacketListeners(PacketFilterManager.java:509) ~[?:?]
        at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.processInboundInternal(NettyChannelInjector.java:455) ~[?:?]
        at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.processInbound(NettyChannelInjector.java:439) ~[?:?]
        at com.comphenix.protocol.injector.netty.channel.InboundPacketInterceptor.channelRead(InboundPacketInterceptor.java:47) ~[?:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[Hypickle-Server-1.8.8-R0.1-SNAPSHOT.jar:git-Carbon-unknown]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[Hypickle-Server-1.8.8-R0.1-SNAPSHOT.jar:git-Carbon-unknown]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[Hypickle-Server-1.8.8-R0.1-SNAPSHOT.jar:git-Carbon-unknown]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327) ~[Hypickle-Server-1.8.8-R0.1-SNAPSHOT.jar:git-Carbon-unknown]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299) ~[Hypickle-Server-1.8.8-R0.1-SNAPSHOT.jar:git-Carbon-unknown]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[Hypickle-Server-1.8.8-R0.1-SNAPSHOT.jar:git-Carbon-unknown]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[Hypickle-Server-1.8.8-R0.1-SNAPSHOT.jar:git-Carbon-unknown]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[Hypickle-Server-1.8.8-R0.1-SNAPSHOT.jar:git-Carbon-unknown]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327) ~[Hypickle-Server-1.8.8-R0.1-SNAPSHOT.jar:git-Carbon-unknown]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299) ~[Hypickle-Server-1.8.8-R0.1-SNAPSHOT.jar:git-Carbon-unknown]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[Hypickle-Server-1.8.8-R0.1-SNAPSHOT.jar:git-Carbon-unknown]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[Hypickle-Server-1.8.8-R0.1-SNAPSHOT.jar:git-Carbon-unknown]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[Hypickle-Server-1.8.8-R0.1-SNAPSHOT.jar:git-Carbon-unknown]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327) ~[Hypickle-Server-1.8.8-R0.1-SNAPSHOT.jar:git-Carbon-unknown]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:314) ~[Hypickle-Server-1.8.8-R0.1-SNAPSHOT.jar:git-Carbon-unknown]
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:435) ~[Hypickle-Server-1.8.8-R0.1-SNAPSHOT.jar:git-Carbon-unknown]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279) ~[Hypickle-Server-1.8.8-R0.1-SNAPSHOT.jar:git-Carbon-unknown]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[Hypickle-Server-1.8.8-R0.1-SNAPSHOT.jar:git-Carbon-unknown]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[Hypickle-Server-1.8.8-R0.1-SNAPSHOT.jar:git-Carbon-unknown]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[Hypickle-Server-1.8.8-R0.1-SNAPSHOT.jar:git-Carbon-unknown]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[Hypickle-Server-1.8.8-R0.1-SNAPSHOT.jar:git-Carbon-unknown]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[Hypickle-Server-1.8.8-R0.1-SNAPSHOT.jar:git-Carbon-unknown]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[Hypickle-Server-1.8.8-R0.1-SNAPSHOT.jar:git-Carbon-unknown]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[Hypickle-Server-1.8.8-R0.1-SNAPSHOT.jar:git-Carbon-unknown]
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[Hypickle-Server-1.8.8-R0.1-SNAPSHOT.jar:git-Carbon-unknown]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[Hypickle-Server-1.8.8-R0.1-SNAPSHOT.jar:git-Carbon-unknown]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[Hypickle-Server-1.8.8-R0.1-SNAPSHOT.jar:git-Carbon-unknown]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[Hypickle-Server-1.8.8-R0.1-SNAPSHOT.jar:git-Carbon-unknown]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[Hypickle-Server-1.8.8-R0.1-SNAPSHOT.jar:git-Carbon-unknown]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[Hypickle-Server-1.8.8-R0.1-SNAPSHOT.jar:git-Carbon-unknown]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[Hypickle-Server-1.8.8-R0.1-SNAPSHOT.jar:git-Carbon-unknown]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[Hypickle-Server-1.8.8-R0.1-SNAPSHOT.jar:git-Carbon-unknown]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) ~[Hypickle-Server-1.8.8-R0.1-SNAPSHOT.jar:git-Carbon-unknown]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722) ~[Hypickle-Server-1.8.8-R0.1-SNAPSHOT.jar:git-Carbon-unknown]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658) ~[Hypickle-Server-1.8.8-R0.1-SNAPSHOT.jar:git-Carbon-unknown]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584) ~[Hypickle-Server-1.8.8-R0.1-SNAPSHOT.jar:git-Carbon-unknown]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496) ~[Hypickle-Server-1.8.8-R0.1-SNAPSHOT.jar:git-Carbon-unknown]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) ~[Hypickle-Server-1.8.8-R0.1-SNAPSHOT.jar:git-Carbon-unknown]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[Hypickle-Server-1.8.8-R0.1-SNAPSHOT.jar:git-Carbon-unknown]
        at java.lang.Thread.run(Thread.java:834) ~[?:?]
Caused by: java.lang.IllegalArgumentException: No constructor with [null] in class net.minecraft.server.v1_8_R3.PacketPlayInUseEntity
        at com.comphenix.protocol.wrappers.WrappedEnumEntityUseAction.useAction(WrappedEnumEntityUseAction.java:77) ~[?:?]
        at com.comphenix.protocol.wrappers.WrappedEnumEntityUseAction.<clinit>(WrappedEnumEntityUseAction.java:35) ~[?:?]
        ... 53 more
[15:01:57 ERROR]: Parameters:
  net.minecraft.server.v1_8_R3.PacketPlayInUseEntity@104c88d0[
    a=1671
    action=ATTACK
    c=<null>
  ]

**Comment by Vagdedes** [comment]
Fixed for the next update
