### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by ImYenil** [Vagdedes/Spartan-AntiCheat#42]
[23:03:50 WARN]: [Spartan] Task #88896 for Spartan vPhase 536.4 generated an exception
java.lang.NullPointerException: null
        at org.bukkit.craftbukkit.v1_8_R3.CraftWorld.getBlockAt(CraftWorld.java:75) ~[Hypickle-Server-1.8.8-R0.1-SNAPSHOT.jar:git-Carbon-unknown]
        at com.vagdedes.spartan.abstraction.g.b.dI(SpartanLocation.java:214) ~[?:?]
        at com.vagdedes.spartan.abstraction.g.b.dK(SpartanLocation.java:267) ~[?:?]
        at com.vagdedes.spartan.utils.minecraft.world.a.a(BlockPatternUtils.java:74) ~[?:?]
        at com.vagdedes.spartan.abstraction.check.implementation.movement.b.q(NoFall.java:154) ~[?:?]
        at com.vagdedes.spartan.abstraction.check.c.a(CheckExecutor.java:50) ~[?:?]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59) ~[Hypickle-Server-1.8.8-R0.1-SNAPSHOT.jar:git-Carbon-unknown]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:351) ~[Hypickle-Server-1.8.8-R0.1-SNAPSHOT.jar:git-Carbon-unknown]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:804) ~[Hypickle-Server-1.8.8-R0.1-SNAPSHOT.jar:git-Carbon-unknown]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:387) ~[Hypickle-Server-1.8.8-R0.1-SNAPSHOT.jar:git-Carbon-unknown]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:734) ~[Hypickle-Server-1.8.8-R0.1-SNAPSHOT.jar:git-Carbon-unknown]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:631) ~[Hypickle-Server-1.8.8-R0.1-SNAPSHOT.jar:git-Carbon-unknown]
        at java.lang.Thread.run(Thread.java:834) ~[?:?]

**Comment by Vagdedes** [comment]
It's been reported before, 1.8 issue, can't be fixed from my part.
