### ISSUE TITLE
Folia

### ISSUE THREAD

**Issue by Vagdedes** [Vagdedes/Spartan-AntiCheat#52]
[01:15:45] [Server thread/INFO]: [Spartan] Enabling Spartan vPhase 536.5
[01:15:45] [Server thread/ERROR]: Error occurred while enabling Spartan vPhase 536.5 (Is it up to date?)
java.lang.ExceptionInInitializerError: null
	at Spartan-536.5.jar/com.vagdedes.spartan.abstraction.check.b.<init>(Check.java:54) ~[Spartan-536.5.jar:?]
	at Spartan-536.5.jar/me.vagdedes.spartan.system.Enums$HackType.<init>(Enums.java:276) ~[Spartan-536.5.jar:?]
	at Spartan-536.5.jar/me.vagdedes.spartan.system.Enums$HackType.<clinit>(Enums.java:12) ~[Spartan-536.5.jar:?]
	at Spartan-536.5.jar/com.vagdedes.spartan.functionality.b.a.b.<clinit>(CloudBase.java:28) ~[Spartan-536.5.jar:?]
	at Spartan-536.5.jar/com.vagdedes.spartan.functionality.b.a.e.cd(JarVerification.java:59) ~[Spartan-536.5.jar:?]
	at Spartan-536.5.jar/com.vagdedes.spartan.functionality.b.a.e.C(JarVerification.java:30) ~[Spartan-536.5.jar:?]
	at Spartan-536.5.jar/com.vagdedes.spartan.Register.onEnable(Register.java:34) ~[Spartan-536.5.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[folia-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[folia-1.20.6.jar:1.20.6-DEV-d797082]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[folia-1.20.6.jar:1.20.6-DEV-d797082]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[folia-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:632) ~[folia-1.20.6.jar:1.20.6-DEV-d797082]
	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:581) ~[folia-1.20.6.jar:1.20.6-DEV-d797082]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:717) ~[folia-1.20.6.jar:1.20.6-DEV-d797082]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:464) ~[folia-1.20.6.jar:1.20.6-DEV-d797082]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:323) ~[folia-1.20.6.jar:1.20.6-DEV-d797082]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1218) ~[folia-1.20.6.jar:1.20.6-DEV-d797082]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:350) ~[folia-1.20.6.jar:1.20.6-DEV-d797082]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.UnsupportedOperationException
	at org.bukkit.craftbukkit.scheduler.CraftScheduler.handle(CraftScheduler.java:535) ~[folia-1.20.6.jar:1.20.6-DEV-d797082]
	at org.bukkit.craftbukkit.scheduler.CraftScheduler.runTaskTimer(CraftScheduler.java:235) ~[folia-1.20.6.jar:1.20.6-DEV-d797082]
	at org.bukkit.craftbukkit.scheduler.CraftScheduler.runTaskTimer(CraftScheduler.java:211) ~[folia-1.20.6.jar:1.20.6-DEV-d797082]
	at org.bukkit.craftbukkit.scheduler.CraftScheduler.scheduleSyncRepeatingTask(CraftScheduler.java:206) ~[folia-1.20.6.jar:1.20.6-DEV-d797082]
	at Spartan-536.5.jar/com.vagdedes.spartan.functionality.server.d.b(SpartanScheduler.java:99) ~[Spartan-536.5.jar:?]
	at Spartan-536.5.jar/com.vagdedes.spartan.functionality.server.c.a(SpartanBukkit.java:175) ~[Spartan-536.5.jar:?]
	at Spartan-536.5.jar/com.vagdedes.spartan.functionality.g.b.<clinit>(ResearchEngine.java:45) ~[Spartan-536.5.jar:?]
	... 19 more
[01:15:45] [Server thread/INFO]: [Spartan] Disabling Spartan vPhase 536.5
[01:15:45] [Server thread/ERROR]: Error occurred while disabling Spartan vPhase 536.5
java.lang.NoClassDefFoundError: Could not initialize class com.vagdedes.spartan.functionality.b.a.b
	at Spartan-536.5.jar/com.vagdedes.spartan.functionality.b.a.a.er(AutoUpdater.java:26) ~[Spartan-536.5.jar:?]
	at Spartan-536.5.jar/com.vagdedes.spartan.functionality.server.c.x(SpartanBukkit.java:213) ~[Spartan-536.5.jar:?]
	at Spartan-536.5.jar/com.vagdedes.spartan.Register.onDisable(Register.java:89) ~[Spartan-536.5.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:291) ~[folia-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugin(PaperPluginInstanceManager.java:237) ~[folia-1.20.6.jar:1.20.6-DEV-d797082]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.disablePlugin(PaperPluginManagerImpl.java:114) ~[folia-1.20.6.jar:1.20.6-DEV-d797082]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:550) ~[folia-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:206) ~[folia-1.20.6.jar:1.20.6-DEV-d797082]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[folia-1.20.6.jar:1.20.6-DEV-d797082]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[folia-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:632) ~[folia-1.20.6.jar:1.20.6-DEV-d797082]
	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:581) ~[folia-1.20.6.jar:1.20.6-DEV-d797082]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:717) ~[folia-1.20.6.jar:1.20.6-DEV-d797082]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:464) ~[folia-1.20.6.jar:1.20.6-DEV-d797082]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:323) ~[folia-1.20.6.jar:1.20.6-DEV-d797082]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1218) ~[folia-1.20.6.jar:1.20.6-DEV-d797082]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:350) ~[folia-1.20.6.jar:1.20.6-DEV-d797082]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.ExceptionInInitializerError [in thread "Server thread"]
	at Spartan-536.5.jar/com.vagdedes.spartan.abstraction.check.b.<init>(Check.java:54) ~[Spartan-536.5.jar:?]
	at Spartan-536.5.jar/me.vagdedes.spartan.system.Enums$HackType.<init>(Enums.java:276) ~[Spartan-536.5.jar:?]
	at Spartan-536.5.jar/me.vagdedes.spartan.system.Enums$HackType.<clinit>(Enums.java:12) ~[Spartan-536.5.jar:?]
	at Spartan-536.5.jar/com.vagdedes.spartan.functionality.b.a.b.<clinit>(CloudBase.java:28) ~[Spartan-536.5.jar:?]
	at Spartan-536.5.jar/com.vagdedes.spartan.functionality.b.a.e.cd(JarVerification.java:59) ~[Spartan-536.5.jar:?]
	at Spartan-536.5.jar/com.vagdedes.spartan.functionality.b.a.e.C(JarVerification.java:30) ~[Spartan-536.5.jar:?]
	at Spartan-536.5.jar/com.vagdedes.spartan.Register.onEnable(Register.java:34) ~[Spartan-536.5.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[folia-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[folia-1.20.6.jar:1.20.6-DEV-d797082]
	... 10 more

**Comment by Vagdedes** [comment]
Potentially fixed, lots of code reworked to fix this
